### ISSUE TITLE
Selective mode not using correct url for user account GET

### ISSUE THREAD

**Issue by vc5047** [jamf/JamfMigrator#23]
I'm trying to migrate a user account and it keeps failing. Running app in debug mode, I find that it's not building the URL correctly:
`20181221_10:50:46 [- debug -] Item(s) chosen from selective: ["svc-user"]
20181221_10:50:46 [- debug -] check for existing object: svc-user
20181221_10:50:46 [- debug -] [endPointByID] endpoint passed to endPointByID: accounts/userid
20181221_10:50:46 [- debug -] [endPointByID] fetching XML from: https://urltojss/corp/JSSResource//id/18
20181221_10:50:46 [- debug -] [endPointByID] HTTP response code of GET for svc-user: 404
`

it's failing to insert `accounts/userid` in the URL, so it's getting a 404 back.

**Comment by BIG-RAT** [comment]
Thanks for the details - issue should be resolved.
