### ISSUE TITLE
Authentication issue with sites when logged in to both Jamf Migrator and Jamf Pro

### ISSUE THREAD

**Issue by canalnoises** [jamf/JamfMigrator#25]
I have been using the same Jamf Pro administrator account in Jamf Migrator that I usually log in to the Jamf Pro web console with. That's maybe not the best practice, but it was generally working. Today I've been getting some seemingly random authentication errors in Jamf Migrator, and I think I've narrowed it down to this:

**If I'm logged in to Jamf Pro and have any site selected other than "Full Jamf Pro," Jamf Migrator cannot use the same credentials to authenticate.** As soon as I switch from a site back to Full Jamf Pro, it works.

**Comment by BIG-RAT** [comment]
@canalnoises - thanks for the note.  I'll have to poke around and see if the Jamf server has something that can distinguish between what app the account is being used from.  I suspect the server generates permission for an account once it logs in and if you log in from another app with the same account it uses those permissions.

**Comment by BIG-RAT** [comment]
As this behavior applies to other apps, such as postman, a fix will need to come from the server side.  Until then either use separate accounts or make sure you're logged into the full Jamf Pro to migrate.
