### ISSUE TITLE
App crashes in DELETE mode

### ISSUE THREAD

**Issue by ckemp19** [jamf/JamfMigrator#28]
hi - tried running both 3.3.2 and 3.3.0 in delete mode, to clear our staging environment before transferring from production. Every time I run the app it crashes immediately. Output of the last crash report is attached.
[migrator-crash.txt](https://github.com/jamf/JamfMigrator/files/3157626/migrator-crash.txt)

**Comment by ckemp19** [comment]
Tried also on a fresh 10.14.3 VM, same result - instant crash

**Comment by BIG-RAT** [comment]
Thanks @ckemp19 - note you're not alone.  I've not been able to replicate the behavior myself but I'll keep digging.

**Comment by ckemp19** [comment]
Thanks, at least it's good to know it's not just me! :) Standing by

**Comment by sdagley** [comment]
Let me know if you need any more crash logs. I can duplicate the crash with 3.2.2, 3.3.0, and 3.3.1

**Comment by BIG-RAT** [comment]
Issue should be resolved in v3.3.2.  Thanks @ckemp19 for helping pinpoint the issue and @sdagley for offering up additional logs.
