### ISSUE TITLE
Migrating a Configuration Profile with an Approved Kernel Extensions payload corrupts the profile

### ISSUE THREAD

**Issue by sdagley** [jamf/JamfMigrator#29]
I have a Configuration Profile with an Approved Kernel Extensions payload containing 8 Approved Team IDs. When migrated to a new JSS the Display Name of each Team ID was missing (the Team IDs migrated correctly), and the profile fails to install on target Macs with the error "Unable to decrypt encrypted profile." I edited the profile to restore the missing Display Name info, but it still fails to install and reports the same error. The corrupted profile is attached.
[Approved kernel extensions - old.mobileconfig.zip](https://github.com/jamf/JamfMigrator/files/3174710/Approved.kernel.extensions.-.old.mobileconfig.zip)

**Comment by BIG-RAT** [comment]
@sdagley - Thanks for catching that.  Wish it was something I could fix but looks like the server doesn't provide a name to go along with the Team ID, neither when downloaded as xml nor json.  All that appears in the data pulled via the api is an array (AllowedTeamIdentifiers) of Team IDs.

**Comment by sdagley** [comment]
Thanks for checking Leslie. Thankfully my list of approved kexts is fairly short, so the effort to re-create it compared to all the time JamfMigrator saves me is minor.
