### ISSUE TITLE
Ability to push server into destination site

### ISSUE THREAD

**Issue by staze** [jamf/JamfMigrator#30]
Not sure if this is an issue rather than a question, but we're looking at consolidating JSS's (we have three now, and two of those will be merging into the 3rd), and curious if there's a known pathway to use JamfMigrating to basically push "Full JSS" into a specific site on the destination. I know the API can be kind of wonky if it doesn't have full access to the whole JSS (and is instead limited to just a site). 

So for example, department X is taking their JSS and moving it to companyjss site X. Everything that can be set site specifically would then be pushed into the site X, and everything that's Full JSS specific would be merged in manually (probably). 

Thanks!

**Comment by BIG-RAT** [comment]
@staze - that's one that's been on my list for a while, migrate/clone objects from one server (same server) into a site.  Some day I hope to have time to get it done but not likely before you could manually complete your tasks.
