### ISSUE TITLE
High Sierra GUI issues

### ISSUE THREAD

**Issue by canalnoises** [jamf/JamfMigrator#31]
3.3.2 has a couple of display issue when run under High Sierra. 

The popup menu arrows next to the Source and Destination URL fields are invisible, but the menu does still work when you click where the arrows should be.

Also, the "Use dark menu bar and Dock" setting appears to affect the appearance of Jamf Migrator. It's not a true dark mode like Mojave has, so I don't think that setting should be changing anything with Jamf Migrator.

Normal
![High Sierra Light](https://user-images.githubusercontent.com/23707259/58578220-80de2400-8205-11e9-9d3c-b1ecd60e5427.png)

"Use dark menu bar and Dock"
![High Sierra Dark](https://user-images.githubusercontent.com/23707259/58578232-88053200-8205-11e9-8135-1d8e39979075.png)

**Comment by BIG-RAT** [comment]
@canalnoises - thanks for catching that - should now be resolved in v3.3.4

**Comment by canalnoises** [comment]
Perfect. Thank you!
