### ISSUE TITLE
Migrated scripts don't retain empty lines from original script

### ISSUE THREAD

**Issue by danny-friedman** [jamf/JamfMigrator#33]
After migrating scripts I noticed that empty lines in scripts (either required or for beautifucation) had been removed.

This created issues with heredocs that I was using for notifications where I intended to insert empty lines. I was able to replicate this behavior with all migrated scripts.

**Comment by BIG-RAT** [comment]
@danny-friedman - thanks for catching that.  Should now be resolved in v3.3.4

**Comment by danny-friedman** [comment]
Thank you for the quick turnaround. Works perfectly now!
