### ISSUE TITLE
Cannot clear parameter label when re-migrating script

### ISSUE THREAD

**Issue by danny-friedman** [jamf/JamfMigrator#34]
If I have a parameterized script with parameter labels that has been successfully migrated, and I:

1. Clear the text of an existing parameter label
2. Re-migrate the script using jamf-migrator

The original label text will still exist post-migration. All other label changes re-migrate as expected—this is just if a label is cleared (removed).

**Comment by BIG-RAT** [comment]
@danny-friedman  - Thanks for catching that one.  Script parameter labels should now be removed if set to blank with v3.3.5.

**Comment by danny-friedman** [comment]
Much appreciated!
