### ISSUE TITLE
Nested Smart Computer Groups

### ISSUE THREAD

**Issue by benducklow** [jamf/JamfMigrator#36]
I am in the midst of using this for my first migration. I am moving through the documented migration order however it looks like the Smart Computer Groups that contain other/nested Smart Computer Groups error out. I thought this might be the case and confirmed it with an attempt of one. Here's a snippet from the log:

```
20190802_083147 [CreateEndpoints] Migrating smartcomputergroups
20190802_083147 [CreateEndpoints] [computergroups] 10.13 machines - not FileVaulted - 'cadmin' has SecureToken - Failed (409).  Create error: Smart Group (10.13 machines - not FileVaulted - &apos;cadmin&apos; has SecureToken) depends on another Smart Group (Mac Engineering / Jamf Ops / DEP Exclusion) which does not exist yet.
```

Any advise or workaround or fix? I have alot of leg-work if there isn't and will have to figure out which order within Smart Computer Groups to do first.

Thanks and looking forward to the continued growth oif this tool. I use it for one-off situations and its slick!

**Comment by BIG-RAT** [comment]
@benducklow - sadly I've not had time to work out nested groups as criteria.  My current fix is to run group migration several times.  I'm thinking each run will create more of the missing nested groups.

**Comment by benducklow** [comment]
ok, that's good to know and thanks for the reply! A few other things I noticed (not sure if I should create another issue report) is for:
1. Smart Computer groups that reference a Patch management version fails
2. A nested Static Computer Group fails (as it's not yet on the destination server yet either)
3. Static Computer Group migration errors because the devices doesn't exist yet on the destination JSS

**Comment by BIG-RAT** [comment]
Updated the limitations section to call out the nested group issue.  Patch management issue is already there.  Help mentions, as you may have already discovered, that computers should be migrated before groups.
