### ISSUE TITLE
Packages are listed in random order

### ISSUE THREAD

**Issue by canalnoises** [jamf/JamfMigrator#38]
Packages seem to be listed in a random order, which can make it rather difficult to find what I'm looking for. Would it be possible to make it sort alphabetically?

**Comment by BIG-RAT** [comment]
Not seeing that on the servers I've tested.  Any chance I could get a screen shot?  Also all/part of a debug log would be nice.  Launch the app from terminal:
 .../jamf-migrator.app/Contents/MacOS/jamf-migrator -debug

The part that lists packages to migrate is of most interest, for example:
904_165858 [- debug -] [getEndpoints] endpointJSON: ["packages": <__NSArrayI 0x7f85b463a330>(
{
    id = 73;
    name = "conn1.dmg";
},
{
    id = 74;
    name = "conn2.dmg";
},
{
    id = 75;
    name = "conn3.dmg";
},
{
    id = 78;
    name = "essent_BBEdit.dmg";
},
{
    id = 79;
    name = "essent_CodeRunner.dmg";
},
{
    id = 77;
    name = "essent_Slack.dmg";
},
{
    id = 76;
    name = "essent_Xcode.dmg";

**Comment by canalnoises** [comment]
Here's what I'm seeing in the GUI.
![Screen Shot 2019-09-04 at 3 34 07 PM](https://user-images.githubusercontent.com/23707259/64293391-b6dc2400-cf29-11e9-98e5-ed7c924e9f0e.png)

Oddly, the log does appear to be listing packages in alphabetical order. The whole thing is very long (lots of packages) so I've pasted just a small section here, but I could email you the whole log file if that would be helpful.


{
    id = 188;
    name = "Evernote-7.1.1.pkg";
},
{
    id = 382;
    name = "Evernote-7.11.457846.pkg";
},
{
    id = 403;
    name = "Evernote-7.12.457935.pkg";
},
{
    id = 184;
    name = "Evernote-7.2.pkg";
},
{
    id = 244;
    name = "Evernote-7.8.pkg";
},
{
    id = 120;
    name = "Extensis-UTC-6.1.5.pkg";
},
{
    id = 121;
    name = "Extensis-UTC-6.1.6.pkg";
},
{
    id = 168;
    name = "FileCatalystTransferAgent-3.7.2.pkg";
},
{
    id = 144;
    name = "FileMaker_Pro-16-PSD_Licensed.pkg";
},
{
    id = 16;
    name = "Final Draft_Final Draft_9.1.0_Generic.dmg";
},
{
    id = 151;
    name = "Final_Draft-10.0.3.pkg";
},
{
    id = 280;
    name = "Final_Draft-10.0.9.pkg";
},
{
    id = 260;
    name = "Final_Draft-11.0.1.pkg";
},
{
    id = 199;
    name = "GoogleChrome-67.0.3396.62.pkg";
},
{
    id = 210;
    name = "GoogleChrome-67.0.3396.79.pkg";
},
{
    id = 177;
    name = "GoogleChrome-67.0.3396.99.pkg";
},

**Comment by BIG-RAT** [comment]
resolved in version 4.0.1.
