### ISSUE TITLE
Security &amp; Privacy - Failed (409).  Update error: unknown.

### ISSUE THREAD

**Issue by macmule** [jamf/JamfMigrator#45]
Profiles with the Security & Privacy payload are failed to migrate with a 409 error.

> 20200114_101908 ----------- Starting Migration -----------
> 20200114_101909 [CreateEndpoints] [osxconfigurationprofiles] Security &amp; Privacy - Failed (409).  Create error: unknown.

**Comment by BIG-RAT** [comment]
?Do they by chance have FileVault/Institutional Key included?

________________________________

**Comment by macmule** [comment]
FV2 isn't always enabled.

But escrowing to the JPS is.

**Comment by BIG-RAT** [comment]
Seems to be the name of the policy.  If you take the ampersand out of the name does the policy migrate? Mine did.  Also, I didn't have this issue with my 10.13 server so I may need to see what may have changed.

**Comment by BIG-RAT** [comment]
Modified how the ampersand is encoded.

**Comment by macmule** [comment]
Looks good.. just migrated to a 10.18 from 10.19 & no issues

**Comment by macmule** [comment]
Ok, looks good.. but actually doesn't seem to API over all...

```
20200227_145035 ----------- Starting Migration -----------
20200227_145036 [CreateEndpoints] Migrating osxconfigurationprofiles
20200227_145036     [CreateEndpoints] [osxconfigurationprofiles] succeeded: Security &amp; Privacy
20200227_145036     [CreateEndpoints] [osxconfigurationprofiles] succeeded: Security &amp; Privacy
20200227_145036     [CreateEndpoints] [osxconfigurationprofiles] succeeded: Security &amp; Privacy
```

We had 3 profiles for:

- Content caching
- Deskops
- Laptops

Only the "Content caching" one came over.

It appears that jamf-migrator isn't pulling over the profiles if the have the same name..

I replaced the "&" with "and" & same logs, but sane import issue:

```
20200227_145355 ----------- Starting Migration -----------
20200227_145356 [CreateEndpoints] Migrating osxconfigurationprofiles
20200227_145356     [CreateEndpoints] [osxconfigurationprofiles] succeeded: Security and Privacy
20200227_145356     [CreateEndpoints] [osxconfigurationprofiles] succeeded: Security and Privacy
20200227_145356     [CreateEndpoints] [osxconfigurationprofiles] succeeded: Security and Privacy
```

Appending the role (content, laptop, desktop) seemed to work

**Comment by BIG-RAT** [comment]
I expect what's happening is the profile gets overridden by the next one with the same name.  Same issue occurs with policies.  I'm not aware of how to create distinct items through the API that have the same name.  When attempting I get the following:


<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>

<p>Error: Duplicate name</p>?




cheers,

leslie

________________________________
