### ISSUE TITLE
Policy Icons do not move with migration

### ISSUE THREAD

**Issue by master-vodawagner** [jamf/JamfMigrator#46]
I've noticed that migrating policies between instances doesn't pull across the Self Service Icon.

Is this possible as a feature request?

**Comment by BIG-RAT** [comment]
The icon should copy over but only when creating new policies.  This is to prevent the same icon from being duplicated every time a policy is updated during a migration.  Let me know if during new policy creation if the icon fails to migrate.


Better icon management is definitely something worth adding, I'd suggest upvoting the following feature request if you haven't already:

https://www.jamf.com/jamf-nation/feature-requests/1474/manage-self-service-policy-icons



________________________________

**Comment by master-vodawagner** [comment]
So I've definitely had a New policy that migrated over but the icon was missing

**Comment by BIG-RAT** [comment]
Well that's a bummer.  If you get a chance to run the app in debug mode (.../path/to/jamf-migrator.app/Contents/MacOS/jamf-migrator -debug) could you forward the log?  Don't need the entire log, perhaps the portion starting with something like:

20200115_092251 [- debug -] Removing blank lines.?


And of course clear out any info you don't want publicly shared (Jamf Pro URL maybe).


Thanks.

________________________________

**Comment by BIG-RAT** [comment]
Modified the process a bit and added more logging.  When you get a chance let me know how things look.

**Comment by master-vodawagner** [comment]
Any chance you can build out a new .APP for me to try?

**Comment by BIG-RAT** [comment]
Let me know what the debug log shows from [v5.0.3](https://github.com/jamfprofessionalservices/JamfMigrator/releases/download/current/jamf-migrator.zip) when you get a chance.  That will give me an idea where the issue lies and I can work on an update.

**Comment by BIG-RAT** [comment]
seems to be resolved.
