### ISSUE TITLE
DELETE mode: completed count is off by 1

### ISSUE THREAD

**Issue by bradtchapman** [jamf/JamfMigrator#47]
I made some test SUS entries in Jamf, migrated them from production to staging, and then used DELETE mode (Cmd-D) to delete them from Staging.  The entries disappeared, but the total completed shows [ x ] of [ y ]" where x is y-1.  At the end of the run, x should equal y.

<img width="960" alt="Screen Shot 2020-01-21 at 10 13 14 AM" src="https://user-images.githubusercontent.com/32527656/72831132-0d2ad480-3c37-11ea-960c-04792229731e.png">

**Comment by BIG-RAT** [comment]
Right, that's what issue #43 relates too.  I just didn't provide as good a description as you did - thanks @bradtchapman for the detail.  Should be resolved shortly.

**Comment by BIG-RAT** [comment]
Addressed in v5.1.0
