### ISSUE TITLE
UI: Delete mode should show "DELETE" method instead of POST  

### ISSUE THREAD

**Issue by bradtchapman** [jamf/JamfMigrator#48]
As the title says.  Although "Removing" is flashing in red/yellow, the HTTP METHOD above the progress boxes should change from POST to DELETE to reiterate the actual method being used.

**Comment by BIG-RAT** [comment]
Dang it, hoped nobody would point that out.  That and changing the existing label to POST/PUT.  At any rate I'll get it updated.

**Comment by BIG-RAT** [comment]
Addressed in v5.1.0
