### ISSUE TITLE
error HTTP Status Code: 404

### ISSUE THREAD

**Issue by master-vodawagner** [jamf/JamfMigrator#49]
Hey all,

I'm getting an HTTP 404 when using the current version of Jamf Migrator.  Log output below

20200324_110451 [Json.getRecord] error HTTP Status Code: 404
20200324_110451 [Json.getRecord] error HTTP Status Code: 404
20200324_110451 [Json.getRecord] error HTTP Status Code: 404
20200324_110504 [CreateEndpoints] Migrating smartcomputergroups
20200324_110504     [CreateEndpoints] [computergroups] succeeded: Software Installed Needs Patching - Jamf Pro Suite
20200324_110505     [CreateEndpoints] [computergroups] succeeded: Software Installed - Jamf Pro Suite

**Comment by BIG-RAT** [comment]
?Nice catch, and I wonder how long that's been there.

I'll have a fix shortly.

________________________________

**Comment by BIG-RAT** [comment]
Resolved in v5.2.1.  Corrected lookup so that smart/static computer groups use the computergroups api endpoint.
