### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by master-vodawagner** [jamf/JamfMigrator#54]
"The source server requires an account with read only permissions on all objects where the destination server requires an account with create/read/update/delete on all objects."

Seems very excessive permissions to give.  Is there nothing that can be done to give granular control?

**Comment by BIG-RAT** [comment]
Believe you can remove all permissions to the following:

Advanced Volume Purchasing Content Searches
AirPlay Permissions
Allowed File Extensions
API Integrations
Attachment Assignments
Automated Device Enrollment
Classes
Computer Enrollment Invitations
Computer PreStage Enrollments
Device Name Patterns
Enrollment Customizations
Enrollment Profiles
External Patch Sources
File Attachments
GSX Connection Keystores
iBeacons
Infrastructure Manager Instances
Inventory Preload Records
Invitations
JSON Web Token Configurations
Keystores
Maintenance Pages
Managed Preference Profiles
Mobile Device Enrollment Invitations
Mobile Device PreStage Enrollments
Network Integration
Peripheral Types
PreStages
Provisioning Profiles
Push Certificates
Removable MAC Addresses
Restricted Software Records
Self Service Branding Configurations




________________________________

**Comment by master-vodawagner** [comment]
So looks like I need to grant full permissions to the Buildings category and then I can granular control the other permissions

**Comment by BIG-RAT** [comment]
?Source should be good with only read, destination read plus what ever permissions are needed to perform the desired actions.  Hope that makes sense.

________________________________

**Comment by BIG-RAT** [comment]
Updated blurb about permissions on the Wiki page.
