### ISSUE TITLE
Names in packages, policies, etc. with trailing whitespaces will fail migration

### ISSUE THREAD

**Issue by eyevanovich** [jamf/JamfMigrator#58]
Using the current release, I noticed I was getting a few failures but I wasn't sure why. I found out it was due to trailing white spaces in the names of the items i wanted to migrate. Once I fixed the white space it migrated just fine.

**Comment by BIG-RAT** [comment]
Nice catch.  API upload process is stripping the trailing white space which is causing the issue.  Works for the first migration though the policy on the destination server will not have the trailing spaces.  This causes a name mismatch for later migrations as the source server contains the trailing spaces and the destination does not.  Although I can't think of a reason to keep the trailing white space I'd like to see the API preserve it rather then truncating it.

**Comment by BIG-RAT** [comment]
API needs to be fixed so the names are not altered during the migration.
