### ISSUE TITLE
password to destination server failing 

### ISSUE THREAD

**Issue by kotoky** [jamf/JamfMigrator#59]
I got the password destination server failure any time. Need to change the password on the destination server any time if I need to run the tool. Also, computer migration does not migrate the computer object to the desired site instance on the new server. What is the fix? I'm running version 5.2.8 JAMF -migration.
Thank you in advance

**Comment by BIG-RAT** [comment]
What sort of messages do you see in the logs?

**Comment by BIG-RAT** [comment]
inactive
