### ISSUE TITLE
Import Failures

### ISSUE THREAD

**Issue by M-MDev** [jamf/JamfMigrator#60]
When importing packages, groups and policies together from source x of x policies fail and logs just stop. 

Example:

2 Packages
2 Groups
3 Policies

Imports both packages and groups fine but just stops after 2 of the 3 policies are imported.

**Comment by BIG-RAT** [comment]
Stops as in crashes or hangs/becomes non-responsive?  What does the log show?

**Comment by M-MDev** [comment]
The app does not crash or hang however the log stops on the second policy
and that is the last line.

**Comment by BIG-RAT** [comment]
always stops on the same policy?  can you import one policy at a time?  Might through the app in debug mode (instructions in the help) and review/share the log.

**Comment by M-MDev** [comment]
Is there a hard coded timeout? Looks to be occurring around 200 seconds.

20210305_145003 [- debug -] [CreateEndpoints] POST or PUT Operation: PUT
20210305_145003 [- debug -] [CreateEndpoints] endpoint: policies-3	 Total: 3	 Succeeded: 0	 No Failures: true	 SuccessArray 0
20210305_145003 [- debug -] [CreateEndpoints] Last item in policies complete.
20210305_145004 [- debug -] [Migration Complete] runtime: 195.010402832 seconds
20210305_145004 [- debug -] [Migration Complete] runtime: 195.311697998 seconds

**Comment by BIG-RAT** [comment]
?None defined.  Using the default timeouts of waiting 60 seconds for new data and up to 7 days to complete a transfer.

________________________________

**Comment by BIG-RAT** [comment]
Let me know if you're still seeing the issue with the lates update. If so can you share the xml files?
