### ISSUE TITLE
Assign computers to selected site

### ISSUE THREAD

**Issue by damacguy** [jamf/JamfMigrator#62]
So, just looked through the readme.md again, and it looks like only Groups, Policies, and Configuration Profiles can be scoped to a site. But that's really odd, I sure I can assign a machine to a site through the API.

That may be what I have to do for now though - take the list of machines and run them through a script that uses the API to assign the machines to a site after I've imported them. :-\

Objects won't import if the computers assigned to the objects aren't available and in the same site.

**Comment by BIG-RAT** [comment]
Right, no doubt a nice to have but currently focused on providing ways to do things that aren't in the console.

**Comment by BIG-RAT** [comment]
Added to version 6.0.0
