### ISSUE TITLE
`computer` migrate does not respect management status

### ISSUE THREAD

**Issue by Honestpuck** [jamf/JamfMigrator#63]
When migrating computer records the `<remote_management>` key is not respected. It should look like:
```
computer>
    <general>
        <remote_management>
            <managed>true</managed>
            <management_username>managementAccountName</management_username>
            <management_password>YourPassword</management_password>
           <management_password_sha256/>
        </remote_management>
    </general>
</computer>
```

This involves removing or setting to "" the key `<management_password_sha256>` as well as adding the `<management_password>` key and giving it a value so that it matches the above.

**Comment by Honestpuck** [comment]
If you come across this problem I've written a Python script that fixes the management status. It's at https://github.com/Honestpuck/computerize

**Comment by BIG-RAT** [comment]
Are you migrating the computer as managed? Preferences --> computer
![manage](https://user-images.githubusercontent.com/22251543/129915328-dc9ca250-96b2-4a46-8552-7b57ee3b7043.png)

**Comment by Honestpuck** [comment]
Well, I'm a nong. That will fix it.
