### ISSUE TITLE
Unexpected behavior when saving

### ISSUE THREAD

**Issue by dev-yeet** [jamf/JamfMigrator#66]
If you have a policy with a backslash in your policy name, then the policy xml won't save locally.

Example: 
Touch - /Library/Scripts/~~~/.DEPNotifySetupDone
Touch ~/.skipbuddy

Additionally, if you have a colon in your policy name,  the policy will save with a backslash instead of a comma. this doesn't seem to affect migrations, just the saving functionality. 

Example:
Install - Apple Software Updates - AutoLogin: Lab -> Install - Apple Software Updates - AutoLogin/ Lab

**Comment by BIG-RAT** [comment]
Hoping you meant forward slash, /, rather than backslash , \.  Addressed in v5.9.3

**Comment by dev-yeet** [comment]
oops, yeah i meant forward slash. thank you!
