### ISSUE TITLE
jamf-migrator Stucks

### ISSUE THREAD

**Issue by ahousseini** [jamf/JamfMigrator#68]
Hi

I have an issue when doing a selective policy migration. The migration process starts but does not continue. In the logs I see the following and nothing happens anymore:

```
20220131_135455 ----------- Starting Migration -----------
20220131_135459 [Json.getRecord] get endpoint: policies/id/503 from server: https://example.com/
```

I tried the following:
- Use another user, even an administrator with full access
- Use other source and even destination server (on-premise and Jamf Cloud)
- Use different policies
- Completely removed jamf-migrator and reinstalled it (with AppCleaner)

Any ideas?

**Comment by ahousseini** [comment]
Thanks for the fast response.

I launched the app in debug mode. It seems something is going on (authentication on both source and destination server, building `existingEndpoints` array etc.) but the application then hangs on this:

```
20220131_150023 [- debug -] [ViewController.startMigrating] Item(s) chosen from selective: ["Bueel-S-EDO042 (519)", "Bueel-S-EDO043 (520)", "Bueel-S-EDO044 (521)"]
20220131_150023 [- debug -] [Json.getRecord] get endpoint: policies/id/519 from server: https://example.com/
20220131_150023 [- debug -] [Json.getRecord] Looking up: https://example.com/JSSResource/policies/id/519
```

All this 3 policies don't have any dependencies. I also tried it with the `Migrate Dependencies` checkbox.

**Comment by BIG-RAT** [comment]
When launched form Terminal (in debug mode) did you by chance see some output, in Terminal, starting with:
[icons] result of Json().getRecord: <some json info>

**Comment by ahousseini** [comment]
No, only this:

```
/Applications/jamf-migrator.app/Contents/MacOS/jamf-migrator -debug
resetting export location
```

**Comment by mikedowler** [comment]
I'm seeing something similar, migrating a single script.  Running 6.0.1 on Apple M1.  Seems to be hanging on:

`20220201_171659 [- debug -] [Json.getRecord] Looking up: https://example.com:8443/JSSResource/scripts/id/332`

**Comment by mikedowler** [comment]
5.9.3 is working fine for the same action, though

**Comment by BIG-RAT** [comment]
What happens if you go into settings (gear on bottom left), then app tab, set Maximum Concurrent Threads to something like 4?  Looks like I might need to set an initial default value.

**Comment by ahousseini** [comment]
Yes, this solved the issue!

**Comment by BIG-RAT** [comment]
Thanks for the quick feedback.  Fix will be in the next update.

**Comment by macmule** [comment]
FWIW, hit the same issue (was, migrating user accounts..).. and this worked for me too: https://github.com/jamf/JamfMigrator/issues/68#issuecomment-1027282766

**Comment by BIG-RAT** [comment]
Fixed - set  initial default value if app hasn't run.
