### ISSUE TITLE
App crash everytime i try to export Mac Policies

### ISSUE THREAD

**Issue by Benek107** [jamf/JamfMigrator#69]
It starts to export but after few policies it crashed every time.

**Comment by BIG-RAT** [comment]
Debug log from the app would be more useful to me.  Curious if you are using the default export location or selected another location.  Does it actually export anything or just starts the processesing a few then crashes.

**Comment by Benek107** [comment]
So i have run it with debug flag. I just deleted default folder from download location. And it recreated Jamf migration folder but after 1 policy it crashed. Where i can find debug logs?

**Comment by BIG-RAT** [comment]
Easiest way is command+L from the app or from the menu bar View - Log folder.

**Comment by Benek107** [comment]
log is too big so i have uploaded it to google drive - https://drive.google.com/file/d/13FRsftnfczuV0rovXxPll4bsyjX8d-pE/view?usp=sharing

**Comment by BIG-RAT** [comment]
Looks like the Cloud Services Connector is not set up, which is ok.  I'll have to get a server going without it to see what I've broken, look like something pulling icons from the server is causing the crash.

**Comment by Benek107** [comment]
Is there anything i can do ?

**Comment by BIG-RAT** [comment]
Any errors/output in terminal after the app crashed from launching it in debug mode?  Haven't been able to replicate the issue yet.

**Comment by Benek107** [comment]
`/Applications/jamf-migrator.app/Contents/MacOS/jamf-migrator -debug
Illegal instruction: 4`

This is what i get.

I for example run just Extension Attributes export and it completed without any problems. Same with smart group export. No issues. 

Maybe we have something specific in our policies that tools dont like it ?

**Comment by Benek107** [comment]
Everything except Policies is running ok

**Comment by fleish** [comment]
Not sure how many policies you have, but you could try migrating them one at a time and see if you find one or more in particular that cause a crash.

**Comment by BIG-RAT** [comment]
Still an issue with v6.2.0?  Maybe another log (debug) is on order.

**Comment by Benek107** [comment]
6.2 works fine for all items. You can close this case Thanks for support
