### ISSUE TITLE
Migrator Crash - [PackagesDelegate.getFilename] error getting JSON

### ISSUE THREAD

**Issue by Baravis** [jamf/JamfMigrator#70]
Hello, I'm experiencing a crash when I attempt to migrate just packages from one host to another.  Can I provide any more info than the log entry below?  It seems non-specific, so I thought I might attempt to exclude the below package ID from the selective migration tab.  Odd that it causes the whole program to crash, though.

Logfile entry: 
```
20220209_151331 ----------- Starting Migration -----------
20220209_151332 [PackagesDelegate.getFilename] error getting JSON for https://servername/JSSResource/packages/id/233
```

**Comment by Baravis** [comment]
When I attempt a selective migration for packages the application again quits unexpectedly.  I have a full problem report if it helps, but here's the start: 

```
Process:               jamf-migrator [19769]
Path:                  /Applications/jamf-migrator.app/Contents/MacOS/jamf-migrator
Identifier:            com.jamf.jamf-migrator
Version:               6.0.1 (3)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-02-09 15:30:06.3829 -0700
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Bridge OS Version:     6.0 (19P548)
Anonymous UUID:        2827EE92-083C-5BFF-E119-CEF8B2F73399

Sleep/Wake UUID:       06E9BE3E-F5C3-4CD0-91CA-E1DBCF25EE4B

Time Awake Since Boot: 29000 seconds
Time Since Wake:       4055 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [19769]
```

**Comment by Baravis** [comment]
FWIW I also set maximum concurrent threads to 4 as in another recent issues report.  The crashes continue with that setting in-place.

**Comment by BIG-RAT** [comment]
Let me know if v6.2.0 resolves the crash.

**Comment by Baravis** [comment]
Will do!
________________________________

**Comment by BIG-RAT** [comment]
hoping no news is good news.

**Comment by Baravis** [comment]
Hey, sorry we haven't had time to test the new version and had to move forward with the project.  We may try again with some of our labs coming up here and I'll let you know if there are similar errors.

**Comment by BIG-RAT** [comment]
All good, re-open if it's still an issue.
