### ISSUE TITLE
Removal Of Basic Authentication in Jamf Pro Classic API

### ISSUE THREAD

**Issue by fleish** [jamf/JamfMigrator#71]
I received this with the latest release of Jamf Pro: 

> As a  reminder, Jamf will discontinue support for Basic authentication in the Classic API in a future release of Jamf Pro for enhanced security (estimated removal date: Aug-Dec 2022). For more information on using Bearer Token authentication see the Jamf Developer Resources. 

and wanted to confirm JamfMigrator will continue work once this support is removed from Jamf Pro

**Comment by BIG-RAT** [comment]
Confirmed.

**Comment by fleish** [comment]
Thanks
