### ISSUE TITLE
crashes when trying to auth on multi-context jss

### ISSUE THREAD

**Issue by fauxserve** [jamf/JamfMigrator#73]
I set up a multi context jss on a lab system to act as a API holding space for objects I want to use later in the project. 
Trying to use Jamf Migrator to send these objects across from one JSS to another on the same system causes an immediate crash.

**Comment by fauxserve** [comment]
I see there is the "File import" option... is there a way to do the opposite, like to simply GET and save the XML files without doing a PUT to the other server?

**Comment by BIG-RAT** [comment]
Wasn't able to replicate the crash, but wonder if while fixing other issues the multi-context issues has been resolved.

Settings (gear in lower left) -> export, does that have what you're looking for?

**Comment by BIG-RAT** [comment]
Should be resolved in v6.2.4
