### ISSUE TITLE
Migration to site not working if user is not full admin - but it works in 5.93

### ISSUE THREAD

**Issue by swissarmygeek** [jamf/JamfMigrator#75]
We have many sites in our central Jamf.  Most users are site-admins only, with added packages and scripts permissions.

With Jamf Migrator v5.93, they can migrate from their source Jamf to their site in central Jamf

But in any higher versions, this fails with "Create error: The request requires user authentication."  Why is that happening?  Can you make it possible for site-admins to migrate into their site again like in 5.93?

**Comment by swissarmygeek** [comment]
Yes, I just tried a test with my 'regular' site-admin user & I was able to get an auth token using ' $url/api/v1/auth/token'

**Comment by BIG-RAT** [comment]
Curious if the site admins are members of multiple groups.  In particular if they are a member of a group with "Full Access" and custom privilages.

**Comment by swissarmygeek** [comment]
We have multiple levels - but yes, most site admins are in some additional groups with access to create/read/update (but not delete) Scripts & Packages.  If there are additional permissions needed I can probably add those - except deleting.  But since 5.93 works where 6.xx doesn't, it seems like there must be something besides permissions going on to me.

**Comment by BIG-RAT** [comment]
Curious if v6.0.1 works, that's the last version that only used basic authentication.  Looks like there is an issue with permissions with token auth.  Using a site admin with only read access to policies within a group (which they are a member of) with Full Access I get the following:
```20220829_142325 [CreateEndpoints] [policies] Nothing to see here... - East - Failed (401).  Update error: The request requires user authentication.```
Give the Full Access group create, read, and update to policies I get the following:
```20220829_142419     [CreateEndpoints] [policies] succeeded: Nothing to see here... - East```

**Comment by BIG-RAT** [comment]
@swissarmygeek - added the option to force basic authentication (preferences -> app).  If you get a chance see if that helps.
