### ISSUE TITLE
App performing background actions?

### ISSUE THREAD

**Issue by fleish** [jamf/JamfMigrator#76]
Recently I forgot to quit the jamf-migrator app after I performed some tasks using it. I assumed it was just running in the background not doing anything since the last task which was > 24 hours ago. However, when I upgraded one of the 2 JAMF instances (in this case it was the source instance configured in jamf-migrator) I was prompted with a pop-up message from jamf-migrator noting that it could not login to this instance. I found this peculiar since I wasn't using the app which led me to wonder how/why jamf-migrator would have noticed it could not login to the source instance? AFAIK, it makes stateless API calls and does not maintain a persistent connection that would have been closed when the upgrade took place. Any insight on this would be appreciated.

**Comment by BIG-RAT** [comment]
Token refresh will continue as long as the app is running.

**Comment by fleish** [comment]
That would probably do it, thanks.
