### ISSUE TITLE
jamf-migrator 6.2.5 (4) <self_service_display_name> does not migrate properly

### ISSUE THREAD

**Issue by erefneb** [jamf/JamfMigrator#77]
jamf-migrator 6.2.5 (4) 
When migrating Self Service Policies the <self_service_display_name> does not migrate properly.
It comes over as the full name of the policy, as opposed to the custom self service name.

When I use “SaveOnly” to download the policy as XML, the <self_service_display_name> is correct in the XML.
But even when I upload the raw XML it does not migrate the custom name correctly.

**Comment by BIG-RAT** [comment]
Thanks for the heads up.  Fixed in v6.2.6
