### ISSUE TITLE
jamf-migrator 6.2.5 (4) crashes when using "Check for Updates..."

### ISSUE THREAD

**Issue by erefneb** [jamf/JamfMigrator#78]
jamf-migrator 6.2.5 (4) crashes when using "Check for Updates..."
Steps to reproduce:
Use "Check for Updates..." with jamf-migrator 6.2.5 (4)

Crash log is attached.
[jamf-migrator 6.2.5 (4) crash.txt](https://github.com/jamf/JamfMigrator/files/9402861/jamf-migrator.6.2.5.4.crash.txt)

**Comment by BIG-RAT** [comment]
fixed in v6.2.6
