### ISSUE TITLE
Jamf Migrator 6.2.6 crashes upon launch on macOS 12.5.1

### ISSUE THREAD

**Issue by gandalf239** [jamf/JamfMigrator#79]
Appears that it's trying to write to reserved address space:

"reserved VM address space (unallocated)" across from "MALLOC_NANO (reserved)."

**Comment by BIG-RAT** [comment]
First time it's been used?  At least on that machine?  Looks like if the following file isn't present it crashes.
`~/Library/Containers/com.jamf.jamf-migrator/Data/Library/Application Support/jamf-migrator/settings.plist`

Should get created (copied from within the app bundle - jamf-migrator.app/Contents/Resources/settings.plist) if it's missing but it's not.  I'll fix it shortly but in the meantime it can be created manually.

Appriciate the heads up.

**Comment by gandalf239** [comment]
First time on this particular profile on this machine; thanks for heads up on the file. I grabbed 6.2.5 yesterday to do what I needed; will get 6.2.7 now. Thanks for jumping on this!
