### ISSUE TITLE
Migrating Computers to New Site

### ISSUE THREAD

**Issue by dustinowens81625** [jamf/JamfMigrator#83]
When I move a computer, it only adds the entry on the new Jamf Pro, Is shows up as managed but I don't seem to be able to do anything with it. 

Is there a way to push the new Jamf Pro MDM profile to the computer from the old Jamf Pro side ?  Or how are you completing the client side migration to the new MDM ?

**Comment by BIG-RAT** [comment]
Much like packages only the record is migrated to the new server.  Unenrolling/re-enrolling is outside the scope of jamf-migrator.  There are a variety of ways to do this, the following might provide some ideas: 
[ReEnroller](https://github.com/jamf/ReEnroller)
