### ISSUE TITLE
Provide SSO compatible login function

### ISSUE THREAD

**Issue by delize** [jamf/JamfMigrator#85]
Could you provide an SSO compatible login function, this could breaking out into a Chrome Window and intercepting the cookie session to 

I have read the documentation on the main page, and I see a note in an older version back in 2.1.3, but, for an account that does not use any passwords - I am unable to login and export some of our configurations to provide for an Audit Report.

**Comment by BIG-RAT** [comment]
The Jamf Pro API only supports basic auth and bearer token, which is retrieved using basic auth.  Given that I don’t see a way to provide SSO compatibility.
