### ISSUE TITLE
Tenant behind Azure SSO, local login failover URL not working

### ISSUE THREAD

**Issue by Khartoun2004** [jamf/JamfMigrator#86]
I recently got a new Jamf Cloud Dev environment spun up. I was able to get the migrator tool working once with the local login failover URL for our Production and Dev environments. However, when I try to authenticate in the same way, the application immediate crashes. I updated the Migrator app to the latest version and changed my local passwords in both jamf environments. My user accounts have full administrative control over both environments. I checked the site box at the top of the application. Is there some trick to making this work that I'm missing? I've attached a word doc of the error log it generates. 
[JamfMigratorErrorReport.docx](https://github.com/jamf/JamfMigrator/files/10248554/JamfMigratorErrorReport.docx)

**Comment by BIG-RAT** [comment]
Any issues going to https://your.jamf.server/api, select classic API, enter your credentials and click Authorize?  If you're able to pass along the Jamf Migrator log from the crash rather than the .docx that could be helpful.

**Comment by Khartoun2004** [comment]
Thanks! That worked perfectly. Appreciate it.
