### ISSUE TITLE
UX Issue

### ISSUE THREAD

**Issue by easyedc** [jamf/JamfMigrator#88]
It's not quite a problem, there are 2 different colors of green used for "successful" get/send jobs? I feel that has to be an error.[](url)
<img width="807" alt="Screenshot 2023-03-14 at 12 00 30 PM" src="https://user-images.githubusercontent.com/12171122/225065662-0d53b8e4-baf5-4d8f-90bc-ccbc08a37da5.png">

**Comment by BIG-RAT** [comment]
Keen eye!  Should be resolved in v7.1.1.
