### ISSUE TITLE
Feature request: Increase number of recent servers in pulldown menus

### ISSUE THREAD

**Issue by polyevolver54** [jamf/JamfMigrator#92]
For my use case as an MSP, I've got 30+ instances and growing. If I need to clone an item from the master to all of them, I can only do 9-10 using the pulldown menu, then would start pasting them in. When multiplied by multiple items per day it quickly becomes too much manual interaction.

I'm going to try out the CLI implementation, and have scripts I've created to replicate between and maintain sync between servers, but even so would love to be able to maintain as many as possible in the GUI pulldown for ad-hoc needs with this useful app.

Thanks for any consideration!

**Comment by BIG-RAT** [comment]
check out v7.3.1.  Preferences -> app, you can set the number of servers in the list.
