### ISSUE TITLE
text size issue on older iPhones with smaller screens during enrollment

### ISSUE THREAD

**Issue by paulschofield-jamf** [jamf/JamfMigrator#93]
Admin is migrating devices from another MDM solution to Jamf pro and using Jamf Migrate app - V3.3.6
When a user has their text size set to large on their iPhone, the migrate app prevents them from scrolling down to click on "Enroll" after hitting "begin". 
They attempted to minimize the text on the phone itself to facilitate the migration, but it appears to persist in an enlarged state within the JAMF Migrate app. 
Because of this, they get a "Web API Error" when they wait too long on the enroll page.
Affects older iPhones - on SE editions impacts even with font size set to the smallest: iPhones (8) and (2nd gen) SE or smaller screens 

workaround on larger screen models it to reset font size and/or reinstall the app

**Comment by BIG-RAT** [comment]
Sorry to say you've got the wrong project, Jamf Migrator and Jamf Migrate serve two different functions.  The team working on Jamf Migrate have been notified of the issue.
