### ISSUE TITLE
Feature Request: option to allow items to transfer without computers/devices/users attached

### ISSUE THREAD

**Issue by wakco** [jamf/JamfMigrator#99]
I operate a dual server setup (developer and production environments) It would be useful that if anything that might have a computer/device/user directly attached to it (such as static groups) ignore the computer/device/user attached, since in my environment it is unlikely the computer/device/user be on the other environment.

A preference setting maybe, with a sub-option to include or exclude policies where "Migrate Dependencies" is ticked.

**Comment by BIG-RAT** [comment]
Just to be sure, these settings aren't getting the desired results? Uncheck scope for policies.
![copyPrefs](https://github.com/jamf/JamfMigrator/assets/22251543/c1fdae16-b359-4439-b889-80ce385bf3fc)

**Comment by wakco** [comment]
That Pane is not very clear, but i'll try that for Static Groups, not to mention, I still want the groups to copy, but I'll test them out.

**Comment by wakco** [comment]
I'm closing this because I'm going to go with a workaround, where I'll make sure the Static Groups on that pref pane remain unticked, and just make sure I have no policies/etc with computers/devices/users directly attach (require they be in an appropriate group), which is an appropriate plan since we allow the support staff to edit groups, but not edit policies/etc.
